export const SET_MAIN_SECTION = 'SET_MAIN_SECTION'
export const SET_SEARCH_SECTION = 'SET_SEARCH_SECTION'
export const SET_OR_UNSET_ADVANCE_SEARCH = 'SET_OR_UNSET_ADVANCE_SEARCH'
export const CHANGE_PATH = 'CHANGE_PATH';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
